base:
  siot_url: http://127.0.0.1:6700
  cms_url: http://127.0.0.1:18000
  base_url: http://127.0.0.1:18000
tunnel:
  device_ip: 127.0.0.1
log:
  log_name: logs_
  log_level: info
  log_format: '[%(asctime)s] %(filename)s->%(funcName)s line:%(lineno)d [%(levelname)s] %(message)s'
project:
  project_path: D:\xiangmu\CMS2.5.0\cms-editor-2.5.0-beta.3\CMS Editor\host\data\projects
  x_project: 96ca49f51cda4941ae2f0799175a466c
  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU3VwZXJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiU3VwZXJBZG1pbiIsImV4cCI6MTcwMzU3MDc1MiwiaXNzIjoiQ01TdjIiLCJhdWQiOiJBcGkifQ.cA3RR_dmMdoLbMBzjwvR276Dhx8SEeUdoSmuR1TO83w
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  database: fe465c177ff74c4db3ace4d9f52162d2
  database2: TestDB
  charset: utf8
