-  name: 获取映射表配置
   base_url: ${get_base_url(cms_url)}
   request:
      url: /api/v1/connection/table/${get_extract_data(maptable_id)}/config
      method: get
      headers:
         X-Project: ${get_extract_data(x_project)}
   validate:
      -  equals: {status_code: 200}